### ISSUE TITLE
Database Schema Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-hypertechs#4]
- Make your table names and column names snake_case.
- Why is there a connection between bankteller and bankaccount? Remove the AccountID in the bankteller table.
- Why is there an Address column in the bank_teller table? You can change it to fullname instead.
- I believe transaction history holds over-the-counter transactions such as withdrawal and deposit. Rename this table to over_the_counter_transactions. In this table add the teller_id who performed the transaction. This will become a foreign key from the bank teller teller_id.
- Remove OTPCode in bankaccount table. OTP Code is not a significant data for a bank account. You can use PHP session for this.
- Rename the externalbanktransfer to external_transfer_transactions.
- Rename the internaltransfer to internal_transfer_transactions.
- You can add the OTP code to both external_transfer_transactions and internal_transfer_transactions or you can omit it.

This way you have 3 live tables:
- bank_account which holds the current value of the balance
- bank_teller which holds the bank teller details 
- account_holder which holds the account holder details
These tables are being updated frequently especially the bank_account table where you change the balance for every transaction. Your table account_holder is one-to-many with bank_account because an account holder can have multiple bank accounts - correct.

Then you have audit or history tables:
- over_the_counter_transactions
- internal_transfer_transactions
- external_transfer_transactions
These tables are not updated. In the real world, we do not store this in an SQL databases. We usually store it in a big data repository such as BigQuery and Hadoop. That's because these data are not updated. Once records are entered here, it will never be changed.

Kindly share this to your classmates especially to VRZN team so they will have an idea as well.

**Comment by danay-maryjoy** [comment]
Good evening po, Sir. Follow up lang po ulit namin about changes of this issue, updated na po 'yung database schema namin based po sa feedback niyo, since yesterday. Pa-check po sana namin, and let us know po kung okay na i-close ang issue regarding this. Thank you po.

**Comment by ssvillarosa** [comment]
All good. Closing this ticket.
